### PR TITLE
Transcoding tweaks

### PR DESCRIPTION
**Pull request by F4FXL**
Hi,

This adds following improvements to transcoding:

- A 34th order Bandpass filter to cut unwanted frequencies. DVSI documentation recommends adding this. We got comments from DMR users saying DStar had to much Treble. This improves the transcoding.
- An AGC to compensate for diffrence in levels, especially in DMR, this is turned of by default.
- All those tweaks can be turned on or off through defines in main.h

73
Geoffrey F4FXL / KC3FRA

### CODE REVIEW

**Comment by iamsi** [comment]
Thanks for this! I've put it on 201 and the dstar audio sounds much nicer on dmr, will keep testing.

**Comment by sm0tsc** [comment]
Thanks.. Improves things a lot,, Installed on XLX010. LUC please merge this to the main branch

//SM0TSC

**Comment by LX1IQ** [comment]
Hi folks,
These tweaks are making sense
We are going to merge it into the master branch.
Give us a few days to check the code.

73, Luc

**Comment by F4FXL** [comment]
> Hi folks,
> These tweaks are making sense
> We are going to merge it into the master branch.
> Give us a few days to check the code.
> 
> 73, Luc

Thank you ! :)

**Comment by F4FXL** [comment]
Hi Folks,

We have noticed that the tweaks add some more delay in the transcoding. I am working on a solution.

73 Geoffrey F4FXL / KC3FRA

**Comment by F4FXL** [comment]
Hi Again,

I made some changes and cleaned up the code a little bit. Code is cleaner, no more #if USE_AGC and stuff all over the place. 
Signal processing logic is now done in one place.

**Comment by sm0tsc** [comment]
> Hi Again,
> 
> I made some changes and cleaned up the code a little bit. Code is cleaner, no more #if USE_AGC and stuff all over the place.
> Signal processing logic is now done in one place.

I get this when compiling the new code

root@raspberrypi:~/xlx_ambed-Transcoding-tweaks# make
g++ -Os -Wall -std=c++11 -pthread -c -o cusb3003df2etinterface.o cusb3003df2etinterface.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cvocodecs.o cvocodecs.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cpacket.o cpacket.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o ccallsign.o ccallsign.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cudpsocket.o cudpsocket.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cfirfilter.o cfirfilter.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cambepacket.o cambepacket.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cusb3000baofarminterface.o cusb3000baofarminterface.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cambeserver.o cambeserver.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cusb3000baointerface.o cusb3000baointerface.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cstream.o cstream.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cusb3000interface.o cusb3000interface.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cvocodecchannel.o cvocodecchannel.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o ctimepoint.o ctimepoint.cpp
g++ -Os -Wall -std=c++11 -pthread -c -o cusb3xxxinterface.o cusb3xxxinterface.cpp
cusb3xxxinterface.cpp: In member function ‘virtual void CUsb3xxxInterface::Task()’:
cusb3xxxinterface.cpp:157:26: error: ‘class CVocodecChannel’ has no member named ‘ApplyFilter’
                 Channel->ApplyFilter(*clone);
                          ^~~~~~~~~~~
cusb3xxxinterface.cpp:160:26: error: ‘class CVocodecChannel’ has no member named ‘ApplyAGC’
                 Channel->ApplyAGC(*clone);
                          ^~~~~~~~
make: *** [makefile:14: cusb3xxxinterface.o] Error 1
root@raspberrypi:~/xlx_ambed-Transcoding-tweaks#


Any suggestion?

//SM0TSC - Johan

**Comment by F4FXL** [comment]
> > Hi Again,
> > I made some changes and cleaned up the code a little bit. Code is cleaner, no more #if USE_AGC and stuff all over the place.
> > Signal processing logic is now done in one place.
> 
> I get this when compiling the new code
> 
> root@raspberrypi:~/xlx_ambed-Transcoding-tweaks# make g++ -Os -Wall -std=c++11 -pthread -c -o cusb3003df2etinterface.o cusb3003df2etinterface.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cvocodecs.o cvocodecs.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cpacket.o cpacket.cpp g++ -Os -Wall -std=c++11 -pthread -c -o ccallsign.o ccallsign.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cudpsocket.o cudpsocket.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cfirfilter.o cfirfilter.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cambepacket.o cambepacket.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cusb3000baofarminterface.o cusb3000baofarminterface.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cambeserver.o cambeserver.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cusb3000baointerface.o cusb3000baointerface.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cstream.o cstream.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cusb3000interface.o cusb3000interface.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cvocodecchannel.o cvocodecchannel.cpp g++ -Os -Wall -std=c++11 -pthread -c -o ctimepoint.o ctimepoint.cpp g++ -Os -Wall -std=c++11 -pthread -c -o cusb3xxxinterface.o cusb3xxxinterface.cpp cusb3xxxinterface.cpp: In member function ‘virtual void CUsb3xxxInterface::Task()’: cusb3xxxinterface.cpp:157:26: error: ‘class CVocodecChannel’ has no member named ‘ApplyFilter’ Channel->ApplyFilter(*clone); ^~~~~~~~~~~ cusb3xxxinterface.cpp:160:26: error: ‘class CVocodecChannel’ has no member named ‘ApplyAGC’ Channel->ApplyAGC(*clone); ^~~~~~~~ make: *** [makefile:14: cusb3xxxinterface.o] Error 1 root@raspberrypi:~/xlx_ambed-Transcoding-tweaks#
> 
> Any suggestion?
> 
> //SM0TSC - Johan

Dis you make clean before compiling ?

**Comment by sm0tsc** [comment]
Of course I made a make clean

//J

Den sön 23 feb. 2020 kl 15:50 skrev Geoffrey Merck <notifications@github.com

**Comment by F4FXL** [comment]
@sm0tsc How did you retrieve the code ? I just cloned and checked out from my own repository on a blank system and it builds just fine.
What tweaks did you enable in your main.h ?

**Comment by sm0tsc** [comment]
I downloaded the ZIP but from another fork.. I will check with them

Den sön 23 feb. 2020 kl 17:00 skrev Geoffrey Merck <notifications@github.com

**Comment by F4FXL** [comment]
@sm0tsc Maybe you can get the zip from [my fork's TranscodingTweaks branch](https://github.com/F4FXL/xlxd/archive/TranscodingTweaks.zip).

**Comment by K2IE** [comment]
Running on XLX020, seems fine.

**Comment by ravny** [comment]
I installed on XLX511 and working I need to make more testing

**Comment by sm0tsc** [comment]
Any thoughts on adding this to the main branch?

//Johan

**Comment by F4FXL** [comment]
Hi all, 

I've made some improvements as the previous code might generate wobbling sound under certain circumstances.
I also changed the band pass filter to a less CPU intensive one, only 19 taps now.

**Comment by sm0tsc** [comment]
Luc time to add it to main?
//Johan - SM0TSC

**Pull request merged**
