### PR TITLE
Bug fix for channel close message

### PR DESCRIPTION
**Pull request by yngwiechou**
A bug fix for correcting debug messages while closing a channel

### CODE REVIEW

**Comment by phl0** [comment]
Just a remark. The same change was already included in PR https://github.com/LX3JL/xlxd/pull/38. Merging might probably not work if #38 is included ;-)

**Comment by yngwiechou** [comment]
Oops, it seems the pull request automatically compares the changes made between LX3JL/xlxd and yngwiechou/xlxd at HEAD.

Hi Luc,

If you are ok with the changes, please approve #38 only, and reject the rest.

**Comment by phl0** [comment]
All commit to a branch are included until the PR is merged ;-)
You as the author should also be able to close this issue/PR for example.

**Comment by yngwiechou** [comment]
Understood, let me close the rests.
Sorry for the inconveniences.

Regards,
Yngwie

**Comment by phl0** [comment]
No problem at all Yngwie. Just wanted to let you (and others know) :-)

**Pull request closed without merging**
