### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by K2IE**
Fix table to show that 2 x 3003 devices results in 6 channels.

### CODE REVIEW

**Comment by LX1IQ** [comment]
Hi,

No, sorry. The read me is correct!
In theories  2x AMBE3003 chips gives you 6 channels.
But due to the limitations of FTDI chip used on this USB sticks, two sticks can only provide 4 channels.
Our USB-3006 AMBed device does not has this limitation because we used a more powerful FTDI chip which can provide the 6 channels.

73, Luc

**Comment by K2IE** [comment]
I ran ambedtest using my 2 x DVStick 33 devices from DV Mega.  According to the output, I am able to successfully use 6 channels over an extended period of time on a Raspberry Pi 4 (and an RPi 3 as well).  No errors are seen.  Is this not an indication that these particular devices are able to perform?

**Comment by yo2loj** [comment]
According to the DVSI manual, the maximum baud rate of the AMBE 3003 chip in UART mode is 921,600 baud.
6 PCM channel at 16bit/8kHz  sampling (3 in and 3 out) translate to 72,000 kBytes/sec. plus some small (0.6%) overhead, meaning some 970,000 baud (10 bits per byte, because of start and stop bits, and small gaps).
The DV for 6 channels means another 6x4,400bits/channel (DMR/C4FM), another 36,000 baud to be added (overhead, start and stop bits).
So with over 1,000,000 bits/sec, it just will not fit in the 921,600 baud speed provided by the port, and there is nothing you can do.
But you will not get errors, just dropped frames.

**Comment by K2IE** [comment]
Thank you for the explanation.

**Pull request closed without merging**
