### PR TITLE
Add link to the XLX admin page

### PR DESCRIPTION
**Pull request by phl0**
Added one more button with a iframe that contains the output of the XLX admin page for the current reflector.

### CODE REVIEW

**Comment by phl0** [comment]
According to mail from Luc I am going to close this PR as the additional button is not desired.

**Comment by ea4fvb** [comment]
Why not, it is interesting for me?

**Comment by phl0** [comment]
Sure but as I said it was not accepted. The admin page is in beta stadium and shall be protected by a password in the future. That is the information I got from Luc.

**Comment by ea4fvb** [comment]
Ok noted Florian... I will wait that future version, but I will keep your
great contribution.

;)
73
EA4FVB - Pablo

**Comment by phl0** [comment]
Pablo,

no problem. I can leave my branch online and merge future development of xlxd into that branch. For now I will be using it myself as well (to not lose the link to the admin page) :)

   vy73 de Florian DF2ET

**Pull request closed without merging**
