### PR TITLE
Set Suffix as DMR for DMR Users

### PR DESCRIPTION
**Pull request by yngwiechou**
Not sure if this will be easier to identify the DMR users.

### CODE REVIEW

**Comment by phl0** [comment]
I suggested to have another column in the table showing the source mode. 
As for example the DPRS column would also make no sense for DMR users.

**Comment by yngwiechou** [comment]
I have admit this is a quick fix for now.

The dashboard are generated from XML.
If we decide to introduce a new column, then we might need to introduce a new field in the data structure for both DSTAR and DMR.

**Comment by phl0** [comment]
Jepp sure. Didn't want to deny your nice hack. Just had the idea of a more general approach (knowing that it would imply some more data in xml) :-)

**Comment by yngwiechou** [comment]
Pleas hold this, I found that this has a side effect on “Via node”.

Not sure why the Via_node’s callsign will be appended with suffix as well.

**Comment by yngwiechou** [comment]
Let me close it for now. Will raise another pull request if I find a better solution.

**Pull request closed without merging**
