### PR TITLE
Update cdplusprotocol.cpp

### PR DESCRIPTION
**Pull request by n7tae**
I found this bug when I was playing around with a test reflector with one configured module.

### CODE REVIEW

**Comment by n7tae** [comment]
Found a second bug in G3. I'm not sure if the raw socket needs a 64k buffer, but a 1k buffer will occasionally cause a crash. Marius set RAW_BUFFER_LENMAX to 64k, so I guess he had a reason.

**Comment by F4FXL** [comment]
What problem is this bug causing ?

**Comment by n7tae** [comment]
The CDPlusProtocol bug will prevent anyone from being able to use a module using DPlus if you have configured your XLX with less then 7 ( =='G') modules, because Header->GetRptr1Module() will always return a 'G'

The CRawSocket bug will occasionally cause a crash because sometimes recvfrom will read more than UDP_BUFFER_LENMAX and overwrite the Buffer->data().

**Comment by yo2loj** [comment]
The maximum length of a ICMP frame is 64k, so the rx buffer of those raw frames need to be able to handle that data amount.

**Comment by LX1IQ** [comment]
Fixed with pull request #179

**Pull request closed without merging**
