### PR TITLE
Force DMR->D-STAR transcoging for BrandMeister connections

### PR DESCRIPTION
**Pull request by cyanide-burnout**
Force DMR->D-STAR transcoging for BrandMeister connections
https://github.com/LX3JL/xlxd/issues/74
Tested by BM Beta Testing team in IT and BG

### CODE REVIEW

**Comment by LX3JL** [comment]
The "revision" item of the version structure is intented to carry a small incremental change in the xlxd versioning, and not really any other info like protocol subversion. What will happened when xlxd version will roll from 2.2.1 to next 2.2.2?
So I suggest to implement the protocol revisioning through another specificaly designed mechanism....

**Comment by cyanide-burnout** [comment]
If you read my patch carefully, you will see that it's immutable to major version change until you change the protocol

**Comment by cyanide-burnout** [comment]
I can suggest another option: to check client callsign for prefix "BM".

**Comment by LX1IQ** [comment]
Hi this pull request is covert bye XLX v2.2.2 and can be closed.

73, Luc

**Pull request closed without merging**
