### PR TITLE
Added G3 Terminal Support

### PR DESCRIPTION
**Pull request by yo2loj**
Added G3 Terminal Support for ICom-9700 and Icom Plus2 series.

### CODE REVIEW

**Comment by yo2loj** [comment]
This allows Icom 9700 and Plus2 series radios to access the reflector in terminal and access point mode by simulating a G3 gateway.
Just point the radio to the host/IP and connect to the desired module by entering /XLX###M as the destination and start talking.
Dynamically switching modules is also supported - just adjust the destination to the proper module.

**Comment by lucamarche-iz1mlt** [comment]
Hi, 
I tried to compile your version and it seems to work really well.


73 ... iz1mlt Luca

**Comment by iamsi** [comment]
we've been running the old version from your closed pull on xlx201 for some time, just modified due to the ysf protocol being added. it's pretty popular.

**Comment by vk4tux** [comment]
Have not tried it yet, are you using the Icom app with it ?

**Comment by yo2loj** [comment]
I have confirmations it works with ID31, ID51PLUS2 and IC-9700.
Icom software RS-MS 1.30 is needed for it to work (confirmed by IK5XMK).

**Comment by 1erbn** [comment]
Hi Marius,
While updating the files I found some lines (102...104) in cprotocols.cpp which are not in the original file. My cprotocols.cpp looks like in #127

 delete m_Protocols[6];
        m_Protocols[6] = new CYsfProtocol;
        ok &= m_Protocols[6]->Init();

How to deal with this?
Another question I read in the discussion is about compiling. Do I have to do more then just implement the changes in de files and a reboot?

**Comment by yo2loj** [comment]
Isn't it easier to go to yo2loj/xlxd and clone the whole package?
Also, you can open a ticket there instead of discussing it on the pull request, since it is not related.

**Comment by 1erbn** [comment]
Fine with me, I just downloaded the package but is there a procedure to upgrade my current reflector so all the settings incl. the dashboard will remain?
Sorry for my ignorance but I am not realy into Linux but always willing to learn.
Thanks for your support.

**Comment by yo2loj** [comment]
You need to stop xlxd, replace the binary file and restart. That should do the trick.
If you need specific settings, you need to copy the xlxd.terminal file, too. For LAN access on all modules, this is not needed.

**Comment by 1erbn** [comment]
OK, sorry to bother you again but:
- Which file should I replace?
- In which directory of the downloaded zip file is it located
- What is the destination derectory to put it

Thanks again for your help.

**Comment by yo2loj** [comment]
As I said, this is a pull request, not a support issue, and should not hold any discussions other than its inteded purpose. So I will not answer any more questions here.
Please open an issue in yo2loj/xlxd.

**Pull request merged**
