### PR TITLE
Add country name as tooltip

### PR DESCRIPTION
**Pull request by phl0**
Would be nice if the country name could be displayed as tooltip next to the country's flag. This is realized using the alt and title HTML attributes to the img tag. See here:

screenshot from 2017-06-12 14-05-19

### CODE REVIEW

**Comment by g0wfv** [comment]
For that moment when your flag recognition skills fail you .... :+1:

**Comment by phl0** [comment]
Right Tony ;-)

**Comment by phl0** [comment]
Updated dashboard2 accordingly:

screenshot from 2017-06-12 14-41-12

**Comment by phl0** [comment]
Please wait with merging the code as I have to find a solution for DXCCs that use a different coutries flag. Example KL - Alaska with US flag.

**Comment by phl0** [comment]
@LX1IQ Tooltip jetzt mit CSS und etwas kleiner. Was meinst du?

screenshot from 2017-06-13 08-59-52

**Pull request merged**
